# Generated by Django 5.1.5 on 2026-02-13 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="member_photos/",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("fat_loss", "Fat Loss"),
                            ("muscle_gain", "Muscle Gain"),
                            ("general_fitness", "General Fitness"),
                            ("sports", "Sports Performance"),
                            ("rehab", "Rehabilitation"),
                            ("strength", "Strength Training"),
                            ("flexibility", "Flexibility & Mobility"),
                        ],
                        default="general_fitness",
                        max_length=50,
                        verbose_name="Fitness Goal",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Experience Level",
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(
                        blank=True,
                        help_text="AI will factor these into workout/diet plans",
                        null=True,
                        verbose_name="Medical Conditions",
                    ),
                ),
                (
                    "dietary_preference",
                    models.CharField(
                        choices=[
                            ("veg", "Vegetarian"),
                            ("non_veg", "Non-Vegetarian"),
                            ("vegan", "Vegan"),
                            ("eggetarian", "Eggetarian"),
                            ("jain", "Jain"),
                        ],
                        default="veg",
                        max_length=30,
                        verbose_name="Dietary Preference",
                    ),
                ),
                (
                    "height_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Height (cm)"
                    ),
                ),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "body_fat_pct",
                    models.FloatField(blank=True, null=True, verbose_name="Body Fat %"),
                ),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                ("join_date", models.DateField(verbose_name="Join Date")),
                (
                    "membership_start",
                    models.DateField(verbose_name="Membership Start Date"),
                ),
                (
                    "membership_expiry",
                    models.DateField(verbose_name="Membership Expiry Date"),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount Paid (₹)",
                    ),
                ),
                (
                    "attendance_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Consecutive days of gym visits",
                        verbose_name="Attendance Streak",
                    ),
                ),
                (
                    "last_check_in",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Check-in"
                    ),
                ),
                (
                    "churn_risk_score",
                    models.IntegerField(
                        default=0,
                        help_text="AI-predicted score: 0 (safe) to 100 (high risk)",
                        verbose_name="Churn Risk Score",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("frozen", "Frozen"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Emergency Contact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "members_member",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., '3 Month Basic', 'Annual Premium'",
                        max_length=100,
                        verbose_name="Plan Name",
                    ),
                ),
                (
                    "duration_months",
                    models.IntegerField(verbose_name="Duration (Months)"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price (₹)"
                    ),
                ),
                (
                    "includes_trainer",
                    models.BooleanField(
                        default=False, verbose_name="Includes Personal Trainer"
                    ),
                ),
                (
                    "includes_diet_plan",
                    models.BooleanField(
                        default=False, verbose_name="Includes Diet Plan"
                    ),
                ),
                (
                    "includes_supplements",
                    models.BooleanField(
                        default=False, verbose_name="Includes Supplements"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Membership Plan",
                "verbose_name_plural": "Membership Plans",
                "db_table": "members_membershipplan",
                "ordering": ["gym", "price"],
            },
        ),
    ]
