# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="assigned_trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Trainer",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_plans",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="membership_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="members.membershipplan",
                verbose_name="Membership Plan",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipplan",
            index=models.Index(
                fields=["gym", "is_active"], name="idx_mplan_gym_active"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["gym", "status"], name="idx_member_gym_status"),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["gym", "membership_expiry"], name="idx_member_gym_expiry"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["gym", "churn_risk_score"], name="idx_member_gym_churn"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["gym", "phone"], name="idx_member_gym_phone"),
        ),
        migrations.AlterUniqueTogether(
            name="member",
            unique_together={("gym", "phone")},
        ),
    ]
