# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("goal", models.CharField(max_length=50, verbose_name="Goal")),
                (
                    "dietary_preference",
                    models.CharField(max_length=30, verbose_name="Dietary Preference"),
                ),
                (
                    "daily_calories",
                    models.IntegerField(verbose_name="Daily Calories Target"),
                ),
                (
                    "daily_protein_g",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Daily Protein (g)"
                    ),
                ),
                (
                    "daily_carbs_g",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Daily Carbs (g)"
                    ),
                ),
                (
                    "daily_fat_g",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Daily Fat (g)"
                    ),
                ),
                (
                    "plan_data",
                    models.JSONField(
                        help_text='Structure: {"days": [{"meals": [{"name", "items", "macros"}]}]}',
                        verbose_name="Plan Data (JSON)",
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        default="gpt-4o-mini", max_length=50, verbose_name="AI Model"
                    ),
                ),
                (
                    "ai_prompt_tokens",
                    models.IntegerField(default=0, verbose_name="Prompt Tokens"),
                ),
                (
                    "ai_completion_tokens",
                    models.IntegerField(default=0, verbose_name="Completion Tokens"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Diet Plan",
                "verbose_name_plural": "Diet Plans",
                "db_table": "fitness_dietplan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgressLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "body_fat_pct",
                    models.FloatField(blank=True, null=True, verbose_name="Body Fat %"),
                ),
                (
                    "muscle_mass_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Muscle Mass (kg)"
                    ),
                ),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                (
                    "chest_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Chest (cm)"),
                ),
                (
                    "waist_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Waist (cm)"),
                ),
                (
                    "hips_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Hips (cm)"),
                ),
                (
                    "biceps_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Biceps (cm)"
                    ),
                ),
                (
                    "thighs_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Thighs (cm)"
                    ),
                ),
                (
                    "front_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progress_photos/",
                        verbose_name="Front Photo",
                    ),
                ),
                (
                    "side_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progress_photos/",
                        verbose_name="Side Photo",
                    ),
                ),
                (
                    "back_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progress_photos/",
                        verbose_name="Back Photo",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
            ],
            options={
                "verbose_name": "Progress Log",
                "verbose_name_plural": "Progress Logs",
                "db_table": "fitness_progresslog",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="E.g., '12-Week Fat Loss Program'",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                ("goal", models.CharField(max_length=50, verbose_name="Goal")),
                (
                    "duration_weeks",
                    models.IntegerField(default=4, verbose_name="Duration (Weeks)"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "plan_data",
                    models.JSONField(
                        help_text='Structure: {"weeks": [{"days": [{"exercises": [...]}]}]}',
                        verbose_name="Plan Data (JSON)",
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        default="gpt-4o-mini", max_length=50, verbose_name="AI Model"
                    ),
                ),
                (
                    "ai_prompt_tokens",
                    models.IntegerField(default=0, verbose_name="Prompt Tokens"),
                ),
                (
                    "ai_completion_tokens",
                    models.IntegerField(default=0, verbose_name="Completion Tokens"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Workout Plan",
                "verbose_name_plural": "Workout Plans",
                "db_table": "fitness_workoutplan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("check_in", models.DateTimeField(verbose_name="Check-in Time")),
                (
                    "check_out",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-out Time"
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Duration (Minutes)"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Notes"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "db_table": "fitness_attendance",
                "ordering": ["-check_in"],
            },
        ),
    ]
