# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fitness", "0001_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="members.member",
                verbose_name="Member",
            ),
        ),
    ]
