# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fitness", "0002_initial"),
        ("gyms", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_diet_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diet_plans",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="dietplan",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diet_plans",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AddField(
            model_name="progresslog",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_logs",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="progresslog",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_logs",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AddField(
            model_name="progresslog",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_progress",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recorded By",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_workout_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_plans",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_plans",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["gym", "member", "check_in"], name="idx_att_gym_member_in"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["gym", "check_in"], name="idx_att_gym_checkin"),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(fields=["gym", "member"], name="idx_dplan_gym_member"),
        ),
        migrations.AddIndex(
            model_name="dietplan",
            index=models.Index(
                fields=["member", "is_active"], name="idx_dplan_member_active"
            ),
        ),
        migrations.AddIndex(
            model_name="progresslog",
            index=models.Index(
                fields=["gym", "member", "date"], name="idx_prog_gym_member_date"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="progresslog",
            unique_together={("member", "date")},
        ),
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(fields=["gym", "member"], name="idx_wplan_gym_member"),
        ),
        migrations.AddIndex(
            model_name="workoutplan",
            index=models.Index(
                fields=["member", "is_active"], name="idx_wplan_member_active"
            ),
        ),
    ]
