# Generated by Django 5.1.5 on 2026-02-25 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0004_delete_progresslog"),
        ("members", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietplan",
            name="custom_requirements",
            field=models.TextField(
                blank=True,
                help_text="Optional specific requirements (e.g., 'Jain food', 'no dairy').",
                null=True,
                verbose_name="Custom Requirements",
            ),
        ),
        migrations.AddField(
            model_name="workoutplan",
            name="custom_requirements",
            field=models.TextField(
                blank=True,
                help_text="Optional specific requirements (e.g., 'no squats', 'knee pain').",
                null=True,
                verbose_name="Custom Requirements",
            ),
        ),
        migrations.AlterField(
            model_name="dietplan",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diet_plans",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_plans",
                to="members.member",
                verbose_name="Member",
            ),
        ),
    ]
