# Generated by Django 5.1.5 on 2026-02-13 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GymSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                        verbose_name="Billing Cycle",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount (₹)"
                    ),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Razorpay Subscription ID",
                    ),
                ),
                (
                    "razorpay_customer_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Razorpay Customer ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("paused", "Paused"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(verbose_name="Current Period Start"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(verbose_name="Current Period End"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cancelled At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym Subscription",
                "verbose_name_plural": "Gym Subscriptions",
                "db_table": "billing_gymsubscription",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Razorpay Payment ID"
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Razorpay Order ID",
                    ),
                ),
                (
                    "razorpay_signature",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Razorpay Signature",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount (₹)"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="INR", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="E.g., upi, card, netbanking",
                        max_length=50,
                        null=True,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Invoice Number",
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="GST Amount (₹)",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "billing_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., 'Starter', 'Pro', 'Enterprise'",
                        max_length=100,
                        verbose_name="Plan Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Monthly Price (₹)",
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Yearly Price (₹)"
                    ),
                ),
                (
                    "discount_pct",
                    models.IntegerField(default=0, verbose_name="Yearly Discount %"),
                ),
                (
                    "max_members",
                    models.IntegerField(default=100, verbose_name="Max Members"),
                ),
                (
                    "max_ai_queries_per_month",
                    models.IntegerField(
                        default=100, verbose_name="Max AI Queries/Month"
                    ),
                ),
                (
                    "max_staff_accounts",
                    models.IntegerField(default=3, verbose_name="Max Staff Accounts"),
                ),
                (
                    "max_leads",
                    models.IntegerField(default=50, verbose_name="Max Leads"),
                ),
                (
                    "has_lead_management",
                    models.BooleanField(default=False, verbose_name="Lead Management"),
                ),
                (
                    "has_ai_workout",
                    models.BooleanField(default=True, verbose_name="AI Workout Plans"),
                ),
                (
                    "has_ai_diet",
                    models.BooleanField(default=False, verbose_name="AI Diet Plans"),
                ),
                (
                    "has_ai_lead_scoring",
                    models.BooleanField(default=False, verbose_name="AI Lead Scoring"),
                ),
                (
                    "has_whatsapp_integration",
                    models.BooleanField(
                        default=False, verbose_name="WhatsApp Integration"
                    ),
                ),
                (
                    "has_instagram_content",
                    models.BooleanField(
                        default=False, verbose_name="Instagram Content AI"
                    ),
                ),
                (
                    "has_analytics_dashboard",
                    models.BooleanField(
                        default=False, verbose_name="Analytics Dashboard"
                    ),
                ),
                (
                    "has_white_label",
                    models.BooleanField(default=False, verbose_name="White Label"),
                ),
                (
                    "has_api_access",
                    models.BooleanField(default=False, verbose_name="API Access"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "db_table": "billing_subscriptionplan",
                "ordering": ["display_order", "price_monthly"],
            },
        ),
    ]
