# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymsubscription",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="billing.gymsubscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AddField(
            model_name="gymsubscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="billing.subscriptionplan",
                verbose_name="Plan",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["gym", "status"], name="idx_pay_gym_status"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["paid_at"], name="idx_pay_paid_at"),
        ),
        migrations.AddIndex(
            model_name="gymsubscription",
            index=models.Index(fields=["gym", "status"], name="idx_gsub_gym_status"),
        ),
        migrations.AddIndex(
            model_name="gymsubscription",
            index=models.Index(
                fields=["status", "current_period_end"], name="idx_gsub_status_end"
            ),
        ),
    ]
