# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        max_length=10,
                        verbose_name="Direction",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("payment_reminder", "Payment Reminder"),
                            ("welcome", "Welcome Message"),
                            ("lead_follow_up", "Lead Follow-up"),
                            ("workout_share", "Workout Plan Shared"),
                            ("diet_share", "Diet Plan Shared"),
                            ("birthday", "Birthday Wish"),
                            ("expiry_reminder", "Membership Expiry Reminder"),
                            ("attendance_alert", "Missed Attendance Alert"),
                            ("promotion", "Promotional Message"),
                            ("custom", "Custom Message"),
                        ],
                        default="custom",
                        max_length=30,
                        verbose_name="Message Type",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=20, verbose_name="Recipient Phone"),
                ),
                ("content", models.TextField(verbose_name="Message Content")),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="WhatsApp approved template name",
                        max_length=100,
                        null=True,
                        verbose_name="Template Name",
                    ),
                ),
                (
                    "wa_message_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="WhatsApp Message ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Delivery Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "cost_inr",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=6,
                        verbose_name="Cost (₹)",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "db_table": "communications_whatsappmessage",
                "ordering": ["-created_at"],
            },
        ),
    ]
