# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communications", "0002_initial"),
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="whatsapp_messages",
                to="members.member",
                verbose_name="Member",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["gym", "message_type"], name="idx_wa_gym_type"),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["gym", "status"], name="idx_wa_gym_status"),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["gym", "created_at"], name="idx_wa_gym_date"),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(fields=["recipient_phone"], name="idx_wa_phone"),
        ),
    ]
