# Generated by Django 5.1.5 on 2026-02-17 14:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0004_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactQuery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Company Name"
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
            ],
            options={
                "verbose_name": "Contact Query",
                "verbose_name_plural": "Contact Queries",
                "db_table": "contact_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="idx_contact_created"),
                    models.Index(fields=["status"], name="idx_contact_status"),
                    models.Index(fields=["email"], name="idx_contact_email"),
                ],
            },
        ),
    ]
