# Generated by Django 5.1.5 on 2026-02-20 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0005_contactquery"),
        ("gyms", "0004_gym_organization"),
        ("members", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppAutomation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("expiry_reminder", "Membership Expiry Reminder"),
                            ("payment_pending", "Payment Pending"),
                            ("inactive_reminder", "Inactive Member Reminder"),
                            ("birthday", "Birthday Wish"),
                        ],
                        max_length=50,
                        verbose_name="Automation Type",
                    ),
                ),
                ("enabled", models.BooleanField(default=False, verbose_name="Enabled")),
                (
                    "days_before",
                    models.IntegerField(
                        blank=True,
                        help_text="e.g., 3 days before expiry",
                        null=True,
                        verbose_name="Days Before/After",
                    ),
                ),
                (
                    "template",
                    models.TextField(
                        help_text="Supports variables like {{name}}, {{expiry_date}}, {{plan_name}}, {{gym_name}}",
                        verbose_name="Message Template",
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Run At"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_automations",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Automation",
                "verbose_name_plural": "WhatsApp Automations",
                "db_table": "communications_whatsappautomation",
                "unique_together": {("gym", "type")},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="API Response"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_message_logs",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_message_logs",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message Log",
                "verbose_name_plural": "WhatsApp Message Logs",
                "db_table": "communications_whatsappmessagelog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gym", "status"], name="communicati_gym_id_46f0bd_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="communicati_created_c72c0d_idx"
                    ),
                ],
            },
        ),
    ]
