# Generated by Django 5.1.5 on 2026-02-25 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0006_whatsappautomation_whatsappmessagelog"),
        ("gyms", "0005_gymregistrationrequest"),
        ("members", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=254, verbose_name="Email Address"),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="API/SMTP Response"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_message_logs",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_message_logs",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message Log",
                "verbose_name_plural": "Email Message Logs",
                "db_table": "communications_emailmessagelog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gym", "status"], name="communicati_gym_id_eee95b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="communicati_created_bfe2b0_idx"
                    ),
                ],
            },
        ),
    ]
