# Generated by Django 5.1.5 on 2026-02-25 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0007_emailmessagelog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailMessageLog",
        ),
        migrations.DeleteModel(
            name="WhatsAppMessageLog",
        ),
    ]
