# Generated by Django 5.1.5 on 2026-02-25 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gyms", "0005_gymregistrationrequest"),
        ("members", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("workout_plan", "Workout Plan"),
                            ("diet_plan", "Diet Plan"),
                            ("lead_scoring", "Lead Scoring"),
                            ("instagram_content", "Instagram Content"),
                            ("whatsapp_reply", "WhatsApp Auto-Reply"),
                            ("churn_prediction", "Churn Prediction"),
                            ("member_insight", "Member Insight"),
                            ("content_generation", "Content Generation"),
                        ],
                        max_length=50,
                        verbose_name="Feature",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o-mini",
                        max_length=50,
                        verbose_name="AI Model Used",
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="Prompt Tokens"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="Completion Tokens"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="Total Tokens"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="Cost (USD)",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(default=0, verbose_name="Response Time (ms)"),
                ),
                (
                    "was_cached",
                    models.BooleanField(default=False, verbose_name="Was Cached"),
                ),
                (
                    "was_successful",
                    models.BooleanField(default=True, verbose_name="Was Successful"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "prompt_summary",
                    models.TextField(
                        blank=True,
                        help_text="Short summary of what was asked (not the full prompt for privacy)",
                        null=True,
                        verbose_name="Prompt Summary",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "db_table": "activity_logs_aiusagelog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gym", "feature", "created_at"],
                        name="idx_actai_gym_feat_date",
                    ),
                    models.Index(
                        fields=["gym", "created_at"], name="idx_actai_gym_date"
                    ),
                    models.Index(fields=["model_used"], name="idx_actai_model"),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailMessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=254, verbose_name="Email Address"),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="API/SMTP Response"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_message_logs",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_message_logs",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Message Log",
                "verbose_name_plural": "Email Message Logs",
                "db_table": "activity_logs_emailmessagelog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gym", "status"], name="activity_lo_gym_id_e752fa_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="activity_lo_created_17fa05_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgressLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "weight_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Weight (kg)"
                    ),
                ),
                (
                    "body_fat_pct",
                    models.FloatField(blank=True, null=True, verbose_name="Body Fat %"),
                ),
                (
                    "muscle_mass_kg",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Muscle Mass (kg)"
                    ),
                ),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                (
                    "chest_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Chest (cm)"),
                ),
                (
                    "waist_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Waist (cm)"),
                ),
                (
                    "hips_cm",
                    models.FloatField(blank=True, null=True, verbose_name="Hips (cm)"),
                ),
                (
                    "biceps_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Biceps (cm)"
                    ),
                ),
                (
                    "thighs_cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Thighs (cm)"
                    ),
                ),
                (
                    "front_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progress_photos/",
                        verbose_name="Front Photo",
                    ),
                ),
                (
                    "side_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progress_photos/",
                        verbose_name="Side Photo",
                    ),
                ),
                (
                    "back_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="progress_photos/",
                        verbose_name="Back Photo",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progress Log",
                "verbose_name_plural": "Progress Logs",
                "db_table": "activity_logs_progresslog",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["gym", "member", "date"],
                        name="idx_actprog_gym_member_date",
                    )
                ],
                "unique_together": {("member", "date")},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                ("message", models.TextField(verbose_name="Message Content")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="API Response"
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_message_logs",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_message_logs",
                        to="members.member",
                        verbose_name="Member",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message Log",
                "verbose_name_plural": "WhatsApp Message Logs",
                "db_table": "activity_logs_whatsappmessagelog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gym", "status"], name="activity_lo_gym_id_a2ad9c_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="activity_lo_created_4a5d02_idx"
                    ),
                ],
            },
        ),
    ]
