# Generated by Django 5.1.5 on 2026-02-13 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("google", "Google"),
                            ("walkin", "Walk-in"),
                            ("referral", "Referral"),
                            ("whatsapp", "WhatsApp"),
                            ("justdial", "JustDial"),
                            ("website", "Website"),
                            ("sulekha", "Sulekha"),
                            ("other", "Other"),
                        ],
                        default="walkin",
                        max_length=50,
                        verbose_name="Lead Source",
                    ),
                ),
                ("goal", models.CharField(max_length=50, verbose_name="Fitness Goal")),
                (
                    "budget_range",
                    models.CharField(
                        blank=True,
                        help_text="E.g., '2000-5000'",
                        max_length=50,
                        null=True,
                        verbose_name="Budget Range",
                    ),
                ),
                (
                    "preferred_time",
                    models.CharField(
                        blank=True,
                        help_text="E.g., 'morning', 'evening'",
                        max_length=50,
                        null=True,
                        verbose_name="Preferred Time",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("trial_booked", "Trial Booked"),
                            ("trial_done", "Trial Completed"),
                            ("negotiating", "Negotiating"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why was this lead lost?",
                        max_length=255,
                        null=True,
                        verbose_name="Lost Reason",
                    ),
                ),
                (
                    "ai_score",
                    models.IntegerField(
                        default=0,
                        help_text="0-100, higher = more likely to convert",
                        verbose_name="AI Score",
                    ),
                ),
                (
                    "ai_recommended_action",
                    models.TextField(
                        blank=True,
                        help_text="E.g., 'Call today, offer 10% off'",
                        null=True,
                        verbose_name="AI Recommended Action",
                    ),
                ),
                (
                    "ai_follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="AI Follow-up Date"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "follow_up_count",
                    models.IntegerField(default=0, verbose_name="Follow-up Count"),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "db_table": "leads_lead",
                "ordering": ["-created_at"],
            },
        ),
    ]
