# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gyms", "0001_initial"),
        ("leads", "0001_initial"),
        ("members", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_leads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="converted_member",
            field=models.ForeignKey(
                blank=True,
                help_text="If converted, link to the Member record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_lead",
                to="members.member",
                verbose_name="Converted Member",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["gym", "status"], name="idx_lead_gym_status"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["gym", "ai_score"], name="idx_lead_gym_score"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["gym", "source"], name="idx_lead_gym_source"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["gym", "created_at"], name="idx_lead_gym_created"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["gym", "ai_follow_up_date"], name="idx_lead_gym_followup"
            ),
        ),
    ]
