# Generated by Django 5.2.5 on 2026-02-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Converted At"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contacted_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last Contacted"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="next_followup_date",
            field=models.DateField(
                blank=True,
                help_text="Manual follow-up date set by staff",
                null=True,
                verbose_name="Next Follow-up",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="trial_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trial Date"
            ),
        ),
    ]
