# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone number for OTP login",
                        max_length=20,
                        unique=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Gym Owner"),
                            ("manager", "Manager"),
                            ("trainer", "Trainer"),
                            ("receptionist", "Front Desk"),
                        ],
                        default="trainer",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "can_view_revenue",
                    models.BooleanField(default=False, verbose_name="Can View Revenue"),
                ),
                (
                    "can_manage_members",
                    models.BooleanField(
                        default=True, verbose_name="Can Manage Members"
                    ),
                ),
                (
                    "can_manage_leads",
                    models.BooleanField(default=False, verbose_name="Can Manage Leads"),
                ),
                (
                    "can_use_ai",
                    models.BooleanField(
                        default=True, verbose_name="Can Use AI Features"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into the admin site.",
                        verbose_name="Is Staff",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is Deleted"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Login"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        help_text="The gym this user belongs to. Null for super admins.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff",
                        to="gyms.gym",
                        verbose_name="Gym",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym User",
                "verbose_name_plural": "Gym Users",
                "db_table": "users_gymuser",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["gym", "role"], name="idx_user_gym_role"),
                    models.Index(fields=["phone"], name="idx_user_phone"),
                ],
            },
        ),
    ]
