# Generated by Django 5.1.5 on 2026-02-13 11:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Phone Number"
                    ),
                ),
                ("otp_code", models.CharField(max_length=6, verbose_name="OTP Code")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, verbose_name="Verification Attempts"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
            ],
            options={
                "verbose_name": "OTP Session",
                "verbose_name_plural": "OTP Sessions",
                "db_table": "users_otpsession",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "is_verified"], name="idx_otp_phone_verified"
                    ),
                    models.Index(
                        fields=["phone", "expires_at"], name="idx_otp_phone_expiry"
                    ),
                ],
            },
        ),
    ]
