# Generated by Django 5.1.5 on 2026-02-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gyms", "0003_optional_signup_fields"),
        ("users", "0002_otpsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymuser",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique login username (lowercase, 4-30 chars, alphanumeric + underscores)",
                max_length=30,
                null=True,
                unique=True,
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="gymuser",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AddIndex(
            model_name="gymuser",
            index=models.Index(fields=["username"], name="idx_user_username"),
        ),
    ]
