# Generated by Django 5.1.5 on 2026-02-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gyms", "0003_optional_signup_fields"),
        ("users", "0003_gymuser_username_alter_gymuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymuser",
            name="phone",
            field=models.CharField(
                db_index=True,
                help_text="Primary phone number for OTP login",
                max_length=20,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="gymuser",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Login username (lowercase, 4-30 chars, alphanumeric + underscores)",
                max_length=30,
                null=True,
                verbose_name="Username",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gymuser",
            unique_together={("gym", "phone"), ("gym", "username")},
        ),
    ]
