# Generated by Django 5.1.5 on 2026-02-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0001_initial"),
        ("users", "0004_alter_gymuser_phone_alter_gymuser_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymuser",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="enterprises.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="holding_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="enterprises.holdingcompany",
                verbose_name="Holding Company",
            ),
        ),
        migrations.AddField(
            model_name="gymuser",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff",
                to="enterprises.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="gymuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("holding_admin", "Holding Admin"),
                    ("brand_admin", "Brand Admin"),
                    ("org_admin", "Organization Admin (Super Owner)"),
                    ("region_manager", "Regional Manager"),
                    ("owner", "Gym Owner (Legacy)"),
                    ("manager", "Branch Manager"),
                    ("trainer", "Trainer"),
                    ("receptionist", "Front Desk"),
                ],
                default="trainer",
                max_length=50,
                verbose_name="Role",
            ),
        ),
    ]
