# Generated by Django 5.1.5 on 2026-02-15 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_gymuser_brand_gymuser_holding_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymuser",
            name="username",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Login username (lowercase, 4-30 chars, alphanumeric + underscores)",
                max_length=30,
                unique=True,
                verbose_name="Username",
            ),
            preserve_default=False,
        ),
    ]
