# Generated by Django 5.1.5 on 2026-02-15 09:58

import django.utils.timezone
from django.db import migrations, models


def truncate_usernames(apps, schema_editor):
    GymUser = apps.get_model('users', 'GymUser')
    import uuid
    for user in GymUser.objects.all():
        if user.username and len(user.username) > 30:
            base = user.username[:20]
            suffix = str(uuid.uuid4()).replace('-', '')[:9]
            user.username = f"{base}_{suffix}"
            user.save(update_fields=['username'])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_gymuser_brand_gymuser_holding_company_and_more"),
    ]

    operations = [
        migrations.RunPython(truncate_usernames, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="gymuser",
            name="username",
            field=models.CharField(
                db_index=True,
                default=django.utils.timezone.now,
                error_messages={"unique": "A user with that username already exists."},
                help_text="Login username (lowercase, 4-30 chars, alphanumeric + underscores)",
                max_length=30,
                unique=True,
                verbose_name="Username",
            ),
            preserve_default=False,
        ),
    ]
