# Generated by Django 5.1.5 on 2026-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gyms", "0004_gym_organization"),
        ("users", "0006_alter_gymuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymuser",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific locations this user can access. Empty = all locations (for owners)",
                related_name="authorized_users",
                to="gyms.gym",
                verbose_name="Authorized Locations",
            ),
        ),
    ]
