# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official gym/fitness center name",
                        max_length=255,
                        verbose_name="Gym Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier (e.g., for subdomain: mygym.gymai.in)",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Gym logo image",
                        null=True,
                        upload_to="gym_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=255, verbose_name="Owner Name"),
                ),
                (
                    "owner_phone",
                    models.CharField(
                        help_text="Primary contact number of the gym owner",
                        max_length=20,
                        verbose_name="Owner Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Primary email address (used for login and billing)",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Full street address", verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="City"
                    ),
                ),
                ("state", models.CharField(max_length=100, verbose_name="State")),
                ("pincode", models.CharField(max_length=10, verbose_name="PIN Code")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "gym_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Gym"),
                            ("crossfit", "CrossFit Box"),
                            ("yoga", "Yoga Studio"),
                            ("martial_arts", "Martial Arts"),
                            ("multi", "Multi-Sport"),
                            ("personal_training", "Personal Training Studio"),
                        ],
                        default="standard",
                        max_length=50,
                        verbose_name="Gym Type",
                    ),
                ),
                (
                    "member_capacity",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum number of members the gym can handle",
                        verbose_name="Member Capacity",
                    ),
                ),
                (
                    "monthly_revenue_range",
                    models.CharField(
                        blank=True,
                        help_text="Self-reported revenue range (for segmentation)",
                        max_length=50,
                        null=True,
                        verbose_name="Monthly Revenue Range",
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Free Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("churned", "Churned"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                        verbose_name="Subscription Status",
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial End Date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "onboarded_by",
                    models.CharField(
                        blank=True,
                        help_text="Sales rep or referral source who onboarded this gym",
                        max_length=100,
                        null=True,
                        verbose_name="Onboarded By",
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        help_text="How did this gym find us?",
                        max_length=100,
                        null=True,
                        verbose_name="Referral Source",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gyms",
                        to="billing.subscriptionplan",
                        verbose_name="Subscription Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym",
                "verbose_name_plural": "Gyms",
                "db_table": "gyms_gym",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["city", "is_active"], name="idx_gym_city_active"
                    ),
                    models.Index(
                        fields=["subscription_status"], name="idx_gym_sub_status"
                    ),
                    models.Index(fields=["owner_phone"], name="idx_gym_owner_phone"),
                ],
            },
        ),
    ]
