# Generated by Django 5.1.5 on 2026-02-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_initial"),
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="brand_color",
            field=models.CharField(
                default="#6366f1",
                help_text="Primary hex color for the gym's dashboard theme",
                max_length=7,
                verbose_name="Brand Color",
            ),
        ),
        migrations.AddField(
            model_name="gym",
            name="font_family",
            field=models.CharField(
                choices=[
                    ("Inter", "Inter"),
                    ("Outfit", "Outfit"),
                    ("Poppins", "Poppins"),
                    ("Raleway", "Raleway"),
                    ("Nunito", "Nunito"),
                    ("Roboto", "Roboto"),
                ],
                default="Inter",
                help_text="Google Font used across the gym's dashboard",
                max_length=30,
                verbose_name="Font Family",
            ),
        ),
        migrations.AddField(
            model_name="gym",
            name="gym_code",
            field=models.CharField(
                default="GYM0000001",
                editable=False,
                help_text="Auto-generated tenant ID (e.g. GYM4829156). Used for login.",
                max_length=10,
                unique=True,
                verbose_name="Gym Code",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gym",
            name="logo_base64",
            field=models.TextField(
                blank=True,
                help_text="Base64-encoded logo image for fast rendering, no file storage needed",
                null=True,
                verbose_name="Logo (Base64)",
            ),
        ),
        migrations.AddIndex(
            model_name="gym",
            index=models.Index(fields=["gym_code"], name="idx_gym_code"),
        ),
    ]
