# Generated by Django 5.1.5 on 2026-02-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gyms", "0002_add_gym_code_and_branding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="address",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Full street address",
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="city",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="pincode",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="PIN Code"
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-safe identifier (e.g., for subdomain: mygym.gymai.in)",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="gym",
            name="state",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="State"
            ),
        ),
    ]
