# Generated by Django 5.1.5 on 2026-02-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0001_initial"),
        ("gyms", "0003_optional_signup_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="gym",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent organization (Franchise/Owner) this gym belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="enterprises.organization",
                verbose_name="Organization",
            ),
        ),
    ]
