# Generated by Django 5.1.5 on 2026-02-21 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gyms", "0004_gym_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymRegistrationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("gym_name", models.CharField(max_length=255, verbose_name="Gym Name")),
                (
                    "owner_name",
                    models.CharField(max_length=255, verbose_name="Owner Name"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="City"
                    ),
                ),
                (
                    "plan_slug",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Plan Slug"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=150, verbose_name="Requested Username"),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=128, verbose_name="Password Hash"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Request Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym Registration Request",
                "verbose_name_plural": "Gym Registration Requests",
                "db_table": "gyms_registration_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
