# Generated by Django 5.1.5 on 2026-02-13 10:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("workout_plan", "Workout Plan"),
                            ("diet_plan", "Diet Plan"),
                            ("lead_scoring", "Lead Scoring"),
                            ("instagram_content", "Instagram Content"),
                            ("whatsapp_reply", "WhatsApp Auto-Reply"),
                            ("churn_prediction", "Churn Prediction"),
                            ("member_insight", "Member Insight"),
                            ("content_generation", "Content Generation"),
                        ],
                        max_length=50,
                        verbose_name="Feature",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="gpt-4o-mini",
                        max_length=50,
                        verbose_name="AI Model Used",
                    ),
                ),
                (
                    "prompt_tokens",
                    models.IntegerField(default=0, verbose_name="Prompt Tokens"),
                ),
                (
                    "completion_tokens",
                    models.IntegerField(default=0, verbose_name="Completion Tokens"),
                ),
                (
                    "total_tokens",
                    models.IntegerField(default=0, verbose_name="Total Tokens"),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        max_digits=10,
                        verbose_name="Cost (USD)",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(default=0, verbose_name="Response Time (ms)"),
                ),
                (
                    "was_cached",
                    models.BooleanField(default=False, verbose_name="Was Cached"),
                ),
                (
                    "was_successful",
                    models.BooleanField(default=True, verbose_name="Was Successful"),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Message"
                    ),
                ),
                (
                    "prompt_summary",
                    models.TextField(
                        blank=True,
                        help_text="Short summary of what was asked (not the full prompt for privacy)",
                        null=True,
                        verbose_name="Prompt Summary",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Usage Log",
                "verbose_name_plural": "AI Usage Logs",
                "db_table": "ai_engine_aiusagelog",
                "ordering": ["-created_at"],
            },
        ),
    ]
