# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_engine", "0001_initial"),
        ("gyms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagelog",
            name="gym",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_usage_logs",
                to="gyms.gym",
                verbose_name="Gym",
            ),
        ),
    ]
