# Generated by Django 5.1.5 on 2026-02-13 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_engine", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_usage_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["gym", "feature", "created_at"], name="idx_ai_gym_feat_date"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(fields=["gym", "created_at"], name="idx_ai_gym_date"),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(fields=["model_used"], name="idx_ai_model"),
        ),
    ]
