# Generated by Django 5.1.5 on 2026-02-25 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_engine", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIUsageLog",
        ),
    ]
