# Generated by Django 5.1.5 on 2026-02-15 09:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Holding Company Name",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Legal Entity Name",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="holding_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="Contact Phone"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
            ],
            options={
                "verbose_name": "Holding Company",
                "verbose_name_plural": "Holding Companies",
                "db_table": "enterprises_holdingcompany",
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Brand Name"
                    ),
                ),
                (
                    "brand_code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the brand",
                        max_length=20,
                        unique=True,
                        verbose_name="Brand Code",
                    ),
                ),
                (
                    "royalty_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Percentage of gross revenue paid to brand",
                        max_digits=5,
                        verbose_name="Royalty (%)",
                    ),
                ),
                (
                    "royalty_flat_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Fixed monthly royalty fee",
                        max_digits=10,
                        verbose_name="Royalty Flat Fee (₹)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brand_logos/",
                        verbose_name="Brand Logo",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "holding_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="enterprises.holdingcompany",
                        verbose_name="Holding Company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "db_table": "enterprises_brand",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Legal name of the franchise/owner entity",
                        max_length=255,
                        verbose_name="Organization Name",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=255, verbose_name="Owner Name"),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="Owner Email"
                    ),
                ),
                (
                    "owner_phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Owner Phone"
                    ),
                ),
                (
                    "is_franchise",
                    models.BooleanField(
                        default=True,
                        help_text="True if franchisee-owned, False if corporate-owned",
                        verbose_name="Is Franchise",
                    ),
                ),
                (
                    "franchise_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Franchise Start Date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="enterprises.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="billing.subscriptionplan",
                        verbose_name="Subscription Plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "enterprises_organization",
            },
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["holding_company", "name"], name="idx_brand_holding_name"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["brand", "owner_email"], name="idx_org_brand_email"
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["owner_phone"], name="idx_org_owner_phone"),
        ),
    ]
