# Generated by Django 5.1.5 on 2026-02-15 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoyaltyLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4)",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag. If True, the record is considered deleted.",
                        verbose_name="Is Deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="The first day of the month for this ledger entry",
                        verbose_name="Month",
                    ),
                ),
                (
                    "gross_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Gross Revenue (₹)",
                    ),
                ),
                (
                    "royalty_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Royalty % Applied"
                    ),
                ),
                (
                    "royalty_flat_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Flat Fee Applied (₹)",
                    ),
                ),
                (
                    "calculated_royalty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total Royalty Due (₹)",
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="Paid Date"),
                ),
                (
                    "transaction_ref",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Transaction Reference",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="royalty_ledgers",
                        to="enterprises.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Royalty Ledger",
                "verbose_name_plural": "Royalty Ledgers",
                "db_table": "enterprises_royaltyledger",
                "ordering": ["-month", "organization"],
                "indexes": [
                    models.Index(
                        fields=["organization", "month"], name="idx_royalty_org_month"
                    ),
                    models.Index(fields=["is_paid"], name="idx_royalty_paid"),
                ],
                "unique_together": {("organization", "month")},
            },
        ),
    ]
