# Generated by Django 5.1.5 on 2026-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_initial"),
        ("enterprises", "0002_royaltyledger"),
    ]

    operations = [
        migrations.AddField(
            model_name="holdingcompany",
            name="holding_code",
            field=models.CharField(
                editable=False,
                help_text="Unique identifier for login (e.g. HOLD4829).",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Holding Code",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="org_code",
            field=models.CharField(
                editable=False,
                help_text="Unique identifier for login (e.g. ORG4829).",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Organization Code",
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(fields=["brand_code"], name="idx_brand_code"),
        ),
        migrations.AddIndex(
            model_name="holdingcompany",
            index=models.Index(fields=["holding_code"], name="idx_holding_code"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["org_code"], name="idx_org_code"),
        ),
    ]
