# Generated by Django 5.1.5 on 2026-02-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_initial"),
        (
            "enterprises",
            "0003_holdingcompany_holding_code_organization_org_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="entity_code",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Unified login identifier (e.g. GYM7654321). Used for all user logins.",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Entity Code",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Brand if part of enterprise/franchise structure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organizations",
                to="enterprises.brand",
                verbose_name="Brand",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["entity_code"], name="idx_entity_code"),
        ),
    ]
